version: '3.8'

services:
  # Inference service (CPU)
  inference-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - ./:/code
    working_dir: /code
    ports:
      - "8000:80"
    command: ["uvicorn", "inference.inference:app", "--host", "0.0.0.0", "--port", "80"]

  # Inference service (GPU)
  inference-gpu:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    volumes:
      - ./:/code
    working_dir: /code
    ports:
      - "8000:80"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    command: ["uvicorn", "inference.inference:app", "--host", "0.0.0.0", "--port", "80"]
