channels:
- conda-forge
dependencies:
- python=3.10.5
- pip<=23.3.1
- pip:
  - mlflow==2.22.0
  - astunparse==1.6.3
  - cloudpickle==2.2.1
  - numpy==1.22.0
  - pandas==1.5.0
  - pathlib==1.0.1
  - pydot==3.0.4
  - torch==2.7.0
  - tqdm==4.64.1
name: mlflow-env
